name: Compilação do Projeto

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Compilar projeto
      run: msbuild /p:Configuration=Release /p:Platform=x64 dosbox_pure_libretro.sln

    - name: Criar diretório de artefato
      run: mkdir artefato

    - name: Copiar arquivos de saída para o diretório de artefato
      run: copy build\Release_64bit\*.dll artefato\

    - name: Fazer o upload do artefato
      uses: actions/upload-artifact@v3
      with:
        name: artefato
        path: artefato
